spring:
  application:
    name: app-reactive
  r2dbc:
    url: r2dbc:postgresql://${DB_MY_HOST:localhost}:${DB_MY_PORT:5432}/${DB_MY_DB:reactive_test}
    password: ${DB_MY_PASS:123}
    username: ${DB_MY_USER:postgres}


app:
  jwt:
    access:
      secretKey: 3crt346ef14937c1c0ea519f8fc123a80fcd04a7420f8e8bcd0a7567c272e007b
      expirationAt: 3000000
    refresh:
      secretKey: 1abc346ef14937c1c0ea519f8fc123a80fcd04a7420f8e8bcd0a7567c272e007b
      expirationAt: 9000000

